
/*
 * make it so:
   {
        "announce": ...,
        "info": { ... },
        "signatures": {
            "net.thingtracker": {
                "certificate": optional, DER encoded x.509 certificate,
                "info": { ... } optional,
                "signature": signed data = info + sig info if present
            },
            ...
        }
    }

 */

function hex2buffer (s)
{
    var i;
    var j;
    var view;
    var ret;
    
    limit = s.length;
    ret = new ArrayBuffer (limit / 2);
    view = new Uint8Array (ret);
    for (i = 0, j = 0; i < limit; i += 2)
        view[j++] = HexConverter.hex2dec (s.substr (i, 2));

    return (ret);
}

function SignTorrent (torrent, privatekey, certificate, version, nonce, next_nonce)
{
    var rsa = new RSAKey ();
    rsa.readPrivateKeyFromPEMString (privatekey);

    var info = torrent["info"];
    // create the second info section
    // ToDo: should the sha1 hashes be binary ?
    var info2 = {};
    var sigs = torrent["signatures"] || {};
    var oldsig = sigs["net.thingtracker"] || {};
    var oldinfo = oldsig["info"] || {};
    var oldancestors = oldinfo["ancestors"] || {};
    var oldcurrent = oldinfo["current"] || {};
    var oldsecret = oldinfo["descendent"] || {};

    // move current to ancestor status
    if (oldcurrent)
        for (var oldversion in oldcurrent)
            if (oldcurrent.hasOwnProperty (oldversion))
                oldancestors[oldversion] = oldcurrent[oldversion];
    info2["ancestors"] = oldancestors;

    var check = sha1 (nonce);
    if (oldsecret["hash"])
        if (oldsecret["hash"] != check)
        {
            alert ("Hash for nonce \"" + nonce + "\" does not agree with secret hash " + oldsecret["hash"]);
            return;
        }
    
    var me = {};
    me[version] = {};
    if ("" != nonce)
    {
        me[version]["nonce"] = nonce;
        me[version]["hash"] = check;
    }
    me[version]["id"] = sha1 (encode (info));
    info2["current"] = me;
    
    var secret = {};
    secret["hash"] = sha1 (next_nonce);
    info2["descendent"] = secret;
    
    // sign the two encoded info sections
    // ToDo: check the signature produced here against the one generated by ut-signing-tool (https://github.com/bittorrent/ut-signing-tool)
    var i1 = encode (info);
    var i2 = encode (info2);
    var signature = hex2buffer (rsa.signString (i1 + i2, "sha1"));
    
    var sig = {};
    if ((null != certificate) && ("" != certificate))
    {
        // DER encode the PEM encoded x.509 certificate:
        sig["certificate"] = hex2buffer (X509.pemToHex (certificate));
    }
    sig["info"] = info2;
    sig["signature"] = signature;
    sigs["net.thingtracker"] = sig;
    torrent["signatures"] = sigs;
}